WHAT_TO_FIND_COLOR = 1
WHAT_TO_FIND_BODY = 2
WHAT_TO_FIND_SPECIFIC_VEH_MODEL = 3

SPECIFIC_COLOR_BLACK = 0
SPECIFIC_COLOR_WHITE = 1
SPECIFIC_COLOR_GREY = 2
SPECIFIC_COLOR_RED = 3
SPECIFIC_COLOR_PINK = 4
SPECIFIC_COLOR_BLUE = 5
SPECIFIC_COLOR_YELLOW = 6
SPECIFIC_COLOR_GREEN = 7
SPECIFIC_COLOR_ORANGE = 8
SPECIFIC_COLOR_BROWN = 9
SPECIFIC_COLOR_PURPLE = 10
SPECIFIC_COLOR_CHROME = 11
SPECIFIC_COLOR_GOLD = 12